/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

//import java.util.Random;

public class App {

  public static void init() {

    // Random rand = new Random();
    Vending_machine a = new Vending_machine();
    a.beverage[1].print();
  }

  public static void main(String[] args) {
    init();

  }
}
