/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

import java.util.Random;

public class App {


  public static void init() {

    //Random rand = new Random();
    Beverage beverages;

    beverages = beverages.drink_init();

  }

  public static void main(String[] args) {
    init();

  }
}
