/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

import java.util.Random;

public class App {

  public static void init() {

    Random rand = new Random();
    Beverage[] beverages = new Beverage[20];

    int beverageNum = rand.nextInt(20);
    System.out.println(beverageNum);
    for (int i = 0; i < beverageNum; ++i) {
      beverages[i] = new Beverage((rand.nextInt(20) + 1) * 10, beverages[i].name_init(), rand.nextInt(20));
      beverages[i].print();
    }
  }

  public static void main(String[] args) {
    init();

  }
}
