/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

import java.util.Random;

public class App {


  public static void init() {

    //Random rand = new Random();

    
  }

  public static void main(String[] args) {
    init();

  }
}
